rules:
  default: false
  custom:
    - seriesQuery: 'container_cpu_usage_seconds_total{namespace!="",container!="",container!="POD",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^container_cpu_usage_seconds_total$"
        as: memegenerator_pod_cpu_rate
      metricsQuery: sum(rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,namespace="meme-generator"}[2m])) by (namespace,pod)
    - seriesQuery: 'meme_generator_success_total{pod!=""}'
      resources:
        overrides:
          namespace:
            resource: namespace
          pod:
            resource: pod
      name:
        matches: "^meme_generator_success_total$"
        as: memegenerator_pod_productivity
      metricsQuery: |
        (
          sum by (namespace,pod) (
            rate(meme_generator_success_total{<<.LabelMatchers>>}[5m])
          )
          /
          clamp_min(
            sum by (namespace,pod) (
              rate(container_cpu_usage_seconds_total{<<.LabelMatchers>>,container!="",container!="POD"}[5m])
            ),
            0.0001
          )
        ) or on() vector(0)
prometheus:
  url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local
  port: 9090
metricsRelistInterval: 30s
logLevel: 2
