apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: VITE_NATS_URL
              # Will be dynamically updated by Skaffold post-deploy hook
              value: "WILL_BE_REPLACED"