apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-bridge-script
  namespace: messaging
data:
  bridge.sh: |
    #!/bin/sh
    echo "Starting NATS Core to JetStream bridge..."
    
    # Install nats CLI
    wget -q https://github.com/nats-io/natscli/releases/download/v0.1.4/nats-0.1.4-linux-arm64.tar.gz
    tar -xzf nats-0.1.4-linux-arm64.tar.gz
    
    echo "NATS CLI installed"
    
    # Subscribe to Core NATS and forward to JetStream
    echo "Subscribing to meme.request and forwarding to JetStream..."
    
    ./nats sub meme.request --server=nats://nats:4222 | while read -r line; do
      if echo "$line" | grep -q "Received on"; then
        # Extract the message payload
        message=$(echo "$line" | sed 's/.*Received on.*: //')
        echo "Forwarding message to JetStream: $message"
        
        # Publish to JetStream
        echo "$message" | ./nats pub meme.request --server=nats://nats:4222
      fi
    done
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-bridge
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-bridge
  template:
    metadata:
      labels:
        app: nats-bridge
    spec:
      containers:
      - name: bridge
        image: natsio/nats-box:latest
        command: ["/bin/sh"]
        args: ["/scripts/bridge.sh"]
        volumeMounts:
        - name: script
          mountPath: /scripts
        env:
        - name: NATS_URL
          value: "nats://nats:4222"
      volumes:
      - name: script
        configMap:
          name: nats-bridge-script
          defaultMode: 0755