apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: meme-generator-backend-scaler
  namespace: meme-generator
spec:
  scaleTargetRef:
    name: meme-generator
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 3   # Check every 3 seconds
  cooldownPeriod: 30   # Scale down after 30 seconds of no triggers
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
          - type: Percent
            value: 200
            periodSeconds: 10
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
          - type: Percent
            value: 100
            periodSeconds: 15
  triggers:
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "nats.messaging.svc.cluster.local:8222"
      stream: "MEMES"
      consumer: "meme-generator"  # Use the existing consumer
      account: "$G"  # Default NATS account
      lagThreshold: "2"     # Scale up when just 2 messages are pending
      activationLagThreshold: "1"  # Activate at 1 message to be responsive for demo
      useHttps: "false"  # Specify that we're not using HTTPS for monitoring
      metricType: "Streams"  # Monitor stream messages instead of consumer lag
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-meme-generator
  namespace: meme-generator
spec:
  secretTargetRef: []  # No authentication needed for our NATS setup
