apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meme-generator

resources:
- deployment.yaml
- secret.yaml

commonLabels:
  app.kubernetes.io/part-of: meme-generator
  app.kubernetes.io/component: backend
