apiVersion: v1
kind: Service
metadata:
  name: meme-generator
  labels:
    app: meme-generator
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
spec:
  selector:
    app: meme-generator
  ports:
  - port: 9090
    name: metrics
    targetPort: 9090
  type: ClusterIP
