apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-external-config
  namespace: cache
data:
  redis-external-config: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: cache
spec:
  kubernetesConfig:
    image: redis:7.2.4-alpine
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  redisExporter:
    enabled: true
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
  redisConfig:
    additionalRedisConfig: redis-external-config
