apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: VITE_NATS_URL
              value: "wss://meme-generator.scaleops-labs.dev/ws"
            - name: VITE_REQUEST_SUBJECT
              value: "meme.request"
            - name: VITE_RESPONSE_SUBJECT
              value: "meme.response"
