apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # GKE-specific resources
  - backend-config.yaml
  - websocket-backend-config.yaml
  - managed-certificate.yaml
  - frontend-redirector.yaml
  - nats-websocket-endpoint.yaml

patches:
  # Replace the base ingress with nginx ingress
  - path: ingress-nginx.yaml
    target:
      kind: Ingress
      name: meme-generator
  
  # Frontend environment configuration
  - path: frontend-env-patch.yaml
    target:
      kind: Deployment
      name: meme-generator-frontend

# Use Docker Hub images or your registry
images:
  - name: meme-generator-backend
    newName: vfiftyfive/meme-generator-backend
    newTag: latest
  - name: meme-generator-frontend  
    newName: vfiftyfive/meme-generator-frontend
    newTag: latest