apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # GKE-specific resources
  - backend-config.yaml
  - websocket-backend-config.yaml
  - managed-certificate.yaml
  - frontend-config.yaml
  - nats-websocket-proxy-configmap.yaml
  - nats-websocket-proxy-deployment.yaml

patches:
  # Frontend environment configuration
  - path: frontend-env-patch.yaml
    target:
      kind: Deployment
      name: meme-generator-frontend
  - path: ingress-gce.yaml
    target:
      kind: Ingress
      name: meme-generator
  - path: frontend-service-patch.yaml
    target:
      kind: Service
      name: meme-generator-frontend
  - path: nats-websocket-service-patch.yaml
    target:
      kind: Service
      name: nats-websocket-proxy

# Use Docker Hub images or your registry
images:
  - name: meme-generator-backend
    newName: vfiftyfive/meme-generator-backend
    newTag: latest
  - name: meme-generator-frontend  
    newName: vfiftyfive/meme-generator-frontend
    newTag: latest
