apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  # GKE-specific resources
  - ingress-external-dns.yaml

patches:
  # Remove the base ingress since we have a GKE-specific one
  - target:
      kind: Ingress
      name: meme-generator
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: meme-generator
  
  # Frontend environment configuration
  - path: frontend-env-patch.yaml
    target:
      kind: Deployment
      name: meme-generator-frontend

# Use Docker Hub images or your registry
images:
  - name: meme-generator-backend
    newName: vfiftyfive/meme-generator-backend
    newTag: latest
  - name: meme-generator-frontend  
    newName: vfiftyfive/meme-generator-frontend
    newTag: latest