apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
  labels:
    app: meme-generator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-generator-frontend
  template:
    metadata:
      labels:
        app: meme-generator-frontend
    spec:
      containers:
        - name: frontend
          image: ${DOCKER_REGISTRY}/meme-generator-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: VITE_NATS_URL
              value: "wss://be35a17e95b1.ngrok.app"
            - name: VITE_REQUEST_SUBJECT
              value: "meme.request"
            - name: VITE_RESPONSE_SUBJECT
              value: "meme.response"
---
apiVersion: v1
kind: Service
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
  labels:
    app: meme-generator-frontend
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: meme-generator-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: beagle-causal-slightly.ngrok-free.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meme-generator-frontend
                port:
                  number: 80
