apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
spec:
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: VITE_NATS_URL
              # Port 8090 is forwarded by Skaffold to NATS WebSocket
              value: "ws://localhost:8090"