apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-backend
  namespace: meme-generator
spec:
  template:
    spec:
      containers:
      - name: backend
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
spec:
  template:
    spec:
      containers:
      - name: frontend
        imagePullPolicy: Never