apiVersion: v1
kind: Service
metadata:
  name: nats-websocket-lb
  namespace: meme-generator
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: nats-websocket-proxy
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: websocket