apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats
  namespace: messaging
spec:
  size: 1
  version: "2.10.9"
  
  # Server configuration
  serverConfig:
    # Enable JetStream
    jetStream:
      enabled: true
      memoryStore:
        enabled: true
        maxSize: 1Gi
      fileStore:
        enabled: true
        storageDirectory: /data/jetstream
        pvc:
          size: 2Gi
          storageClassName: standard
    
    # Enable WebSocket
    websocket:
      enabled: true
      port: 8080
      noTLS: true
    
    # Disable authentication for demo
    noAuth: true
  
  # Pod template
  pod:
    enableConfigReload: true
    
  # Service configuration  
  template:
    spec:
      containers:
      - name: nats
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 8080
          name: websocket
        - containerPort: 8222
          name: monitor