apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: messaging
  labels:
    app: nats
spec:
  selector:
    app: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: websocket
    port: 8080
  - name: monitor
    port: 8222
---
apiVersion: v1
kind: Service
metadata:
  name: nats-websocket
  namespace: messaging
  labels:
    app: nats
spec:
  selector:
    app: nats
  ports:
  - name: websocket
    port: 8080
    targetPort: 8080