apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: messaging

resources:
- keda-scaledobject.yaml

commonLabels:
  app.kubernetes.io/part-of: meme-generator
  app.kubernetes.io/component: messaging
