apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: messaging
data:
  nats-server.conf: |
    server_name: $NATS_SERVER_NAME
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222

    # Enable JetStream
    jetstream {
      store_dir: /data
      max_memory_store: 1GB
      max_file_store: 10GB
    }

    # Enable WebSocket
    websocket {
      port: 8080
      no_tls: true
      same_origin: false
      compression: true
      handshake_timeout: "5s"
    }

    # Logging options
    debug: false
    trace: false
    logtime: false

    # Pid file
    pid_file: "/tmp/nats-server.pid"