# NATS Helm values for Meme Battle Royale demo
# Disable cluster mode for simplicity in demo

# Disable authentication for demo purposes
auth:
  enabled: false

# Enable JetStream
jetstream:
  enabled: true
  maxMemory: 1G
  storeDirectory: /data

# Enable persistence for JetStream
persistence:
  enabled: true
  size: 1Gi

# Configure NATS
config:
  # Enable websocket
  websocket:
    enabled: true
    port: 8080
    merge:
      no_tls: true
      # Default behavior allows all origins when empty and same_origin is false
      same_origin: false
      # Enable compression for better performance
      compression: true
      # Set reasonable handshake timeout
      handshake_timeout: "5s"

  # Enable monitoring endpoint for KEDA
  monitor:
    enabled: true
    port: 8222

# Enable Prometheus metrics exporter
promExporter:
  enabled: true
  port: 7777
  podMonitor:
    enabled: true
    merge:
      namespace: monitoring

# Configure service ports
service:
  enabled: true
  ports:
    nats:
      enabled: true
    monitor:
      enabled: true
    websocket:
      enabled: true
      port: 8080

# Disable NATS Box for simplicity
natsBox:
  enabled: false