apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: meme-backend-chaos
  namespace: meme-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meme-backend
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats.messaging.svc.cluster.local:8222"
        stream: "MEMES"
        consumer: "meme-generator"
        lagThreshold: "5"
        activationLagThreshold: "1"
        account: "$G"
        useHttps: "false"
    - type: cpu
      metadata:
        type: Utilization
        value: "50"
        containerName: meme-backend
