apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Frontend environment configuration for ngrok
  - path: frontend-env-patch.yaml
    target:
      kind: Deployment
      name: meme-generator-frontend