apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
  labels:
    app: meme-generator-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meme-generator-frontend
  template:
    metadata:
      labels:
        app: meme-generator-frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/scaleops-platform/meme-generator-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: VITE_NATS_URL
              value: "WILL_BE_REPLACED"  # Will be replaced at runtime
            - name: VITE_REQUEST_SUBJECT
              value: "meme.request"
            - name: VITE_RESPONSE_SUBJECT
              value: "meme.response"