apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: meme-backend
  namespace: meme-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meme-backend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: memegenerator_pod_cpu_rate
      target:
        type: AverageValue
        averageValue: 20m  # Target ~20 milli-cores per pod based on harmony run
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50  # Scale when CPU > 50%
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60  # Scale down max 50% of pods per minute
    scaleUp:
      stabilizationWindowSeconds: 30  # Wait 30 seconds before scaling up again
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # Can double pods per minute
      - type: Pods
        value: 4
        periodSeconds: 60  # But add max 4 pods per minute
