apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: meme-backend
  namespace: meme-generator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: meme-backend
  minReplicaCount: 0
  maxReplicaCount: 10
  pollingInterval: 5
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats.messaging.svc.cluster.local:8222"
        stream: "MEMES"
        consumer: "meme-generator"
        lagThreshold: "5"
        activationLagThreshold: "1"
        deliveryRateThreshold: "10"
        useHttps: "false"
