apiVersion: apps/v1
kind: Deployment
metadata:
  name: meme-backend
  namespace: meme-generator
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox:1.36
          command: 
          - sh
          - -c
          - |
            echo "Waiting for NATS to be ready..."
            until nc -z nats.messaging.svc.cluster.local 4222; do
              echo "NATS is not ready yet..."
              sleep 2
            done
            echo "NATS is ready!"
        - name: wait-for-redis
          image: busybox:1.36
          command:
          - sh
          - -c
          - |
            echo "Waiting for Redis to be ready..."
            until nc -z redis-master.cache.svc.cluster.local 6379; do
              echo "Redis is not ready yet..."
              sleep 2
            done
            echo "Redis is ready!"