apiVersion: v1
kind: Service
metadata:
  name: meme-generator-frontend
  namespace: meme-generator
spec:
  selector:
    app: meme-generator-frontend
  ports:
    - port: 80
      targetPort: 80
      name: http
  type: ClusterIP