apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespaces
  - namespaces.yaml
  
  # Backend
  - backend-secret.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - backend-vpa.yaml
  - backend-keda-scaledobject.yaml
  
  # Frontend
  - frontend-service.yaml
  - frontend-deployment.yaml
  
  # NATS WebSocket service reference
  - nats-websocket-service.yaml
  
  # Ingress for unified access
  - ingress.yaml
  
  # HPA for autoscaling
  - frontend-hpa.yaml
  - backend-hpa.yaml

patches:
  # Add init containers to backend
  - path: backend-deployment-init.yaml
    target:
      kind: Deployment
      name: meme-backend

commonLabels:
  app.kubernetes.io/part-of: meme-generator
  app.kubernetes.io/managed-by: skaffold
